/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BytesLike,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ChainlinkVRFManager,
  ChainlinkVRFManagerInterface,
} from "../ChainlinkVRFManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_VRFCoordinatorAddress",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_subscriptionId",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "_keyHash",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_requestId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "_randomWords",
        type: "uint256[]",
      },
    ],
    name: "rawFulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161024f38038061024f83398101604081905261002f9161006e565b600080546001600160401b03909316600160a01b026001600160e01b03199093166001600160a01b0390941693909317919091179091556001556100c9565b60008060006060848603121561008357600080fd5b83516001600160a01b038116811461009a57600080fd5b60208501519093506001600160401b03811681146100b757600080fd5b80925050604084015190509250925092565b610177806100d86000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80631fe543e314610030575b600080fd5b61004361003e366004610077565b610045565b005b6000546001600160a01b0316330361005d5761005d82825b5050565b634e487b7160e01b600052604160045260246000fd5b6000806040838503121561008a57600080fd5b8235915060208084013567ffffffffffffffff808211156100aa57600080fd5b818601915086601f8301126100be57600080fd5b8135818111156100d0576100d0610061565b8060051b604051601f19603f830116810181811085821117156100f5576100f5610061565b60405291825284820192508381018501918983111561011357600080fd5b938501935b8285101561013157843584529385019392850192610118565b809650505050505050925092905056fea2646970667358221220d634dfeec790b553b2e27fd23ce9a783128838880f3d2cbf05a85d65f3b280c764736f6c634300080e0033";

export class ChainlinkVRFManager__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _VRFCoordinatorAddress: string,
    _subscriptionId: BigNumberish,
    _keyHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ChainlinkVRFManager> {
    return super.deploy(
      _VRFCoordinatorAddress,
      _subscriptionId,
      _keyHash,
      overrides || {}
    ) as Promise<ChainlinkVRFManager>;
  }
  getDeployTransaction(
    _VRFCoordinatorAddress: string,
    _subscriptionId: BigNumberish,
    _keyHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _VRFCoordinatorAddress,
      _subscriptionId,
      _keyHash,
      overrides || {}
    );
  }
  attach(address: string): ChainlinkVRFManager {
    return super.attach(address) as ChainlinkVRFManager;
  }
  connect(signer: Signer): ChainlinkVRFManager__factory {
    return super.connect(signer) as ChainlinkVRFManager__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChainlinkVRFManagerInterface {
    return new utils.Interface(_abi) as ChainlinkVRFManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainlinkVRFManager {
    return new Contract(address, _abi, signerOrProvider) as ChainlinkVRFManager;
  }
}
