/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAutoLiquidityInjecter,
  IAutoLiquidityInjecterInterface,
} from "../IAutoLiquidityInjecter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
    ],
    name: "autoInjectLiquidity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAutoLiquidityInjecter__factory {
  static readonly abi = _abi;
  static createInterface(): IAutoLiquidityInjecterInterface {
    return new utils.Interface(_abi) as IAutoLiquidityInjecterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAutoLiquidityInjecter {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAutoLiquidityInjecter;
  }
}
