/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStocksCompanyInfo,
  IMetaStocksCompanyInfoInterface,
} from "../IMetaStocksCompanyInfo";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStocksCompanyInfo__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStocksCompanyInfoInterface {
    return new utils.Interface(_abi) as IMetaStocksCompanyInfoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStocksCompanyInfo {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStocksCompanyInfo;
  }
}
