/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStocksFranchiseManager,
  IMetaStocksFranchiseManagerInterface,
} from "../IMetaStocksFranchiseManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "companyId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_continentId",
        type: "uint256",
      },
      {
        internalType: "enum MetaStocksFranchiseType",
        name: "_metaStocksFranchiseType",
        type: "uint8",
      },
    ],
    name: "createMetaStocksFranchise",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "companyId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_continentId",
        type: "uint256",
      },
      {
        internalType: "enum MetaStocksFranchiseType",
        name: "_metaStocksFranchiseType",
        type: "uint8",
      },
    ],
    name: "createMetaStocksFranchiseUsingBNB",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStocksFranchiseManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStocksFranchiseManagerInterface {
    return new utils.Interface(_abi) as IMetaStocksFranchiseManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStocksFranchiseManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStocksFranchiseManager;
  }
}
