/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStocksBaseManager,
  IMetaStocksBaseManagerInterface,
} from "../IMetaStocksBaseManager";

const _abi = [
  {
    inputs: [],
    name: "createManager",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "managerId",
        type: "uint256",
      },
    ],
    name: "deleteManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getManager",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "managerId",
        type: "uint256",
      },
    ],
    name: "updateManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMetaStocksBaseManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStocksBaseManagerInterface {
    return new utils.Interface(_abi) as IMetaStocksBaseManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStocksBaseManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStocksBaseManager;
  }
}
