/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStocksCompanyManager,
  IMetaStocksCompanyManagerInterface,
} from "../IMetaStocksCompanyManager";

const _abi = [
  {
    inputs: [],
    name: "createCompany",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStocksCompanyManager__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStocksCompanyManagerInterface {
    return new utils.Interface(_abi) as IMetaStocksCompanyManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStocksCompanyManager {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStocksCompanyManager;
  }
}
