/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MetaStocksFranchiseManagerInterface extends ethers.utils.Interface {
  functions: {
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "burnMetaStocksFranchise(address,uint256,uint256,uint8)": FunctionFragment;
    "claimFromAllFranchises(uint256)": FunctionFragment;
    "companyFranchises(uint256,uint256)": FunctionFragment;
    "createMetaStocksFranchise(address,uint256,uint256,uint8)": FunctionFragment;
    "createMetaStocksFranchiseUsingBNB(address,uint256,uint256,uint8)": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "franchisesLastClaimDates(uint256,uint256)": FunctionFragment;
    "franchisesUsdInvested(uint256,uint256)": FunctionFragment;
    "franchisesWorkers(uint256,uint256)": FunctionFragment;
    "getCreateFranchisePrice()": FunctionFragment;
    "getFranchiseDailyEarnings()": FunctionFragment;
    "getFranchiseValue()": FunctionFragment;
    "getFranchisesByContinent(uint256)": FunctionFragment;
    "getFranchisesUsdInvested(uint256,uint256)": FunctionFragment;
    "getHireWorkerFranchisePrice()": FunctionFragment;
    "getMaintainceFranchiseExpenses()": FunctionFragment;
    "getMetaStocksFranchisesUnclaimedRewards(uint256)": FunctionFragment;
    "getNumberOfMetaStocksFranchises(uint256)": FunctionFragment;
    "getPaymentTokenAddress()": FunctionFragment;
    "hireWorker(uint256,uint8)": FunctionFragment;
    "hireWorkerUsingBNB(uint256,uint8)": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "lastFranchiseClaimDate(uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "self()": FunctionFragment;
    "sellMetaStocksFranchise(address,uint256,uint256,uint8)": FunctionFragment;
    "setCreateFranchisePrice(uint16)": FunctionFragment;
    "setFranchiseDailyEarnings(uint16)": FunctionFragment;
    "setHireWorkerFranchisePrice(uint16)": FunctionFragment;
    "setMaintainceFranchiseExpenses(uint16)": FunctionFragment;
    "setPaymentTokenAddress(address)": FunctionFragment;
    "setRouterAddress(address,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "burnMetaStocksFranchise",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromAllFranchises",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "companyFranchises",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMetaStocksFranchise",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMetaStocksFranchiseUsingBNB",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "franchisesLastClaimDates",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "franchisesUsdInvested",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "franchisesWorkers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreateFranchisePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFranchiseDailyEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFranchiseValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFranchisesByContinent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFranchisesUsdInvested",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHireWorkerFranchisePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaintainceFranchiseExpenses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMetaStocksFranchisesUnclaimedRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfMetaStocksFranchises",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hireWorker",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hireWorkerUsingBNB",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "lastFranchiseClaimDate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "self", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sellMetaStocksFranchise",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreateFranchisePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFranchiseDailyEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHireWorkerFranchisePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaintainceFranchiseExpenses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentTokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouterAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnMetaStocksFranchise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromAllFranchises",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "companyFranchises",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMetaStocksFranchise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMetaStocksFranchiseUsingBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "franchisesLastClaimDates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "franchisesUsdInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "franchisesWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreateFranchisePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFranchiseDailyEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFranchiseValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFranchisesByContinent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFranchisesUsdInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHireWorkerFranchisePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaintainceFranchiseExpenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetaStocksFranchisesUnclaimedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfMetaStocksFranchises",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hireWorker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hireWorkerUsingBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastFranchiseClaimDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "self", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellMetaStocksFranchise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreateFranchisePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFranchiseDailyEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHireWorkerFranchisePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaintainceFranchiseExpenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRouterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "CreateFranchise(address,uint256,uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateFranchise"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber] & {
    owner: string;
    spender: string;
    value: BigNumber;
  }
>;

export type CreateFranchiseEvent = TypedEvent<
  [string, BigNumber, BigNumber] & {
    account: string;
    companyId: BigNumber;
    franchiseType: BigNumber;
  }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type TransferEvent = TypedEvent<
  [string, string, BigNumber] & { from: string; to: string; value: BigNumber }
>;

export class MetaStocksFranchiseManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MetaStocksFranchiseManagerInterface;

  functions: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    burnMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    companyFranchises(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    franchisesLastClaimDates(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    franchisesUsdInvested(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    franchisesWorkers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCreateFranchisePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFranchiseDailyEarnings(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFranchiseValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFranchisesByContinent(
      _continentId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFranchisesUsdInvested(
      companyId: BigNumberish,
      franchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getHireWorkerFranchisePrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMaintainceFranchiseExpenses(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getNumberOfMetaStocksFranchises(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPaymentTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    hireWorker(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _metaStocksFranchiseAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastFranchiseClaimDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    self(overrides?: CallOverrides): Promise<[string]>;

    sellMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCreateFranchisePrice(
      _createFranchisePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFranchiseDailyEarnings(
      _franchiseDailyEarnings: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setHireWorkerFranchisePrice(
      _hireWorkerFranchisePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaintainceFranchiseExpenses(
      _maintainceFranchiseExpenses: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPaymentTokenAddress(
      _paymentTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRouterAddress(
      _routerAddress: string,
      _chainlinkDataFeedAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allowance(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  burnMetaStocksFranchise(
    to: string,
    companyId: BigNumberish,
    amount: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimFromAllFranchises(
    _companyId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  companyFranchises(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createMetaStocksFranchise(
    to: string,
    companyId: BigNumberish,
    _continentId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createMetaStocksFranchiseUsingBNB(
    to: string,
    companyId: BigNumberish,
    _continentId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decimals(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  franchisesLastClaimDates(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  franchisesUsdInvested(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  franchisesWorkers(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCreateFranchisePrice(overrides?: CallOverrides): Promise<BigNumber>;

  getFranchiseDailyEarnings(overrides?: CallOverrides): Promise<BigNumber>;

  getFranchiseValue(overrides?: CallOverrides): Promise<BigNumber>;

  getFranchisesByContinent(
    _continentId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFranchisesUsdInvested(
    companyId: BigNumberish,
    franchiseType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getHireWorkerFranchisePrice(overrides?: CallOverrides): Promise<BigNumber>;

  getMaintainceFranchiseExpenses(overrides?: CallOverrides): Promise<BigNumber>;

  getMetaStocksFranchisesUnclaimedRewards(
    companyId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNumberOfMetaStocksFranchises(
    companyId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPaymentTokenAddress(overrides?: CallOverrides): Promise<string>;

  hireWorker(
    companyId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hireWorkerUsingBNB(
    companyId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _metaStocksFranchiseAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastFranchiseClaimDate(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  onERC1155BatchReceived(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  self(overrides?: CallOverrides): Promise<string>;

  sellMetaStocksFranchise(
    to: string,
    companyId: BigNumberish,
    amount: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCreateFranchisePrice(
    _createFranchisePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFranchiseDailyEarnings(
    _franchiseDailyEarnings: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setHireWorkerFranchisePrice(
    _hireWorkerFranchisePrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaintainceFranchiseExpenses(
    _maintainceFranchiseExpenses: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPaymentTokenAddress(
    _paymentTokenAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRouterAddress(
    _routerAddress: string,
    _chainlinkDataFeedAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    burnMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    companyFranchises(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    decimals(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    franchisesLastClaimDates(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    franchisesUsdInvested(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    franchisesWorkers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreateFranchisePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getFranchiseDailyEarnings(overrides?: CallOverrides): Promise<BigNumber>;

    getFranchiseValue(overrides?: CallOverrides): Promise<BigNumber>;

    getFranchisesByContinent(
      _continentId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFranchisesUsdInvested(
      companyId: BigNumberish,
      franchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHireWorkerFranchisePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getMaintainceFranchiseExpenses(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNumberOfMetaStocksFranchises(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaymentTokenAddress(overrides?: CallOverrides): Promise<string>;

    hireWorker(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _metaStocksFranchiseAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    lastFranchiseClaimDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    self(overrides?: CallOverrides): Promise<string>;

    sellMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCreateFranchisePrice(
      _createFranchisePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFranchiseDailyEarnings(
      _franchiseDailyEarnings: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setHireWorkerFranchisePrice(
      _hireWorkerFranchisePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaintainceFranchiseExpenses(
      _maintainceFranchiseExpenses: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPaymentTokenAddress(
      _paymentTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setRouterAddress(
      _routerAddress: string,
      _chainlinkDataFeedAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      spender?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    Approval(
      owner?: string | null,
      spender?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    "CreateFranchise(address,uint256,uint256)"(
      account?: string | null,
      companyId?: null,
      franchiseType?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { account: string; companyId: BigNumber; franchiseType: BigNumber }
    >;

    CreateFranchise(
      account?: string | null,
      companyId?: null,
      franchiseType?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { account: string; companyId: BigNumber; franchiseType: BigNumber }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; value: BigNumber }
    >;

    Transfer(
      from?: string | null,
      to?: string | null,
      value?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; value: BigNumber }
    >;
  };

  estimateGas: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    burnMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    companyFranchises(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    franchisesLastClaimDates(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    franchisesUsdInvested(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    franchisesWorkers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCreateFranchisePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getFranchiseDailyEarnings(overrides?: CallOverrides): Promise<BigNumber>;

    getFranchiseValue(overrides?: CallOverrides): Promise<BigNumber>;

    getFranchisesByContinent(
      _continentId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFranchisesUsdInvested(
      companyId: BigNumberish,
      franchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHireWorkerFranchisePrice(overrides?: CallOverrides): Promise<BigNumber>;

    getMaintainceFranchiseExpenses(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNumberOfMetaStocksFranchises(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaymentTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    hireWorker(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _metaStocksFranchiseAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastFranchiseClaimDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    self(overrides?: CallOverrides): Promise<BigNumber>;

    sellMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCreateFranchisePrice(
      _createFranchisePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFranchiseDailyEarnings(
      _franchiseDailyEarnings: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setHireWorkerFranchisePrice(
      _hireWorkerFranchisePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaintainceFranchiseExpenses(
      _maintainceFranchiseExpenses: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPaymentTokenAddress(
      _paymentTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRouterAddress(
      _routerAddress: string,
      _chainlinkDataFeedAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burnMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    companyFranchises(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    franchisesLastClaimDates(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    franchisesUsdInvested(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    franchisesWorkers(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreateFranchisePrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFranchiseDailyEarnings(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFranchiseValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFranchisesByContinent(
      _continentId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFranchisesUsdInvested(
      companyId: BigNumberish,
      franchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHireWorkerFranchisePrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaintainceFranchiseExpenses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumberOfMetaStocksFranchises(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPaymentTokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hireWorker(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _metaStocksFranchiseAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastFranchiseClaimDate(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    self(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      amount: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCreateFranchisePrice(
      _createFranchisePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFranchiseDailyEarnings(
      _franchiseDailyEarnings: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setHireWorkerFranchisePrice(
      _hireWorkerFranchisePrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaintainceFranchiseExpenses(
      _maintainceFranchiseExpenses: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPaymentTokenAddress(
      _paymentTokenAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRouterAddress(
      _routerAddress: string,
      _chainlinkDataFeedAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
